### ISSUE TITLE
How to log in and get started?

### ISSUE THREAD

**Issue by ViktorNova** [jgiere/Flipdesk#1]
This looks very cool, but I can't get past the login screen. Is there a default admin username/password to get started with? Thanks!

**Comment by jgiere** [comment]
Hi, sorry for my late reply. I forgot to mark the whole repo as in development. I'm short on time and the software should not be used for production. I will try to get back on it asap.
I'm sorry.

**Comment by ViktorNova** [comment]
It's ok! Thanks for the response, I'm just looking around for Helpdesk-type solutions and yours sounds cool, I'll keep an eye on it =)
